#!/bin/sh -e
#
# Firefox private browsing
#
# https://nullprogram.com/blog/2018/09/06/
#
# Credit: Chris Wellons (wellons@nullprogram.com)
#
DIR="${XDG_CACHE_HOME:-$HOME/.cache}"
mkdir -p -- "$DIR"
TEMP="$(mktemp -d -- "$DIR/firefox-XXXXXX")"
trap "rm -rf -- '$TEMP'" INT TERM EXIT
firefox -profile "$TEMP" -no-remote "$@"
